### ISSUE TITLE
Phantom 1.3.6 release depends on Trooper 1.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by MichaelF25** [Flipkart/phantom#43]

**Comment by regunathb** [comment]
Will promote Trooper to 1.3.2 release and update Phantom 1.3.6 to refer to this release. Is that acceptable? Alternatively, can release Phantom 1.3.7. What would you prefer?

**Comment by MichaelF25** [comment]
Releasing 1.3.7 with a released Trooper version would be the 'cleaner' way I guess.

**Comment by regunathb** [comment]
Phantom 1.3.8 released with Trooper 1.3.2
Pls. verify and close issue if fix is acceptable.

**Comment by MichaelF25** [comment]
Verified as fixed with Phantom 1.3.8
