### ISSUE TITLE
Feature request: Provide sample including packaging

### ISSUE THREAD

**Issue by MichaelF25** [Flipkart/phantom#46]
Hi,

could you please provide (or enhance the existing) sample creating a complete package (tar.gz or zip) for a thrift proxy?
Tried to do it by myself but without look.

Thx,
Michael

**Comment by regunathb** [comment]
Micheal,

I need to understand this request better. So please help me with the following questions:

* Are you able to run the provided sample Thrift proxy as described here (skip to next point if you have run it already) :  [Thrift Example](https://github.com/Flipkart/phantom/wiki/Getting-started-and-Examples)?
    * git clone Phantom
    * Build the sample-thrift-proxy module. It copies all dependencies to /target/lib. If you require a package, you need to simply tar this directory.
    * cd into /phantom/sample-thrift-proxy
    * Run the sample using : java -cp "./target/*:./target/lib/*" org.trpr.platform.runtime.impl.bootstrap.BootstrapLauncher ./src/main/resources/external/bootstrap.xml
    * You should be able to access the dashboard @ http://localhost:8081/admin/dashboard
    * Attached images of the dashboard showing the Thrift proxy, its service endpoint and the methods supported.
![screen shot 2015-06-24 at 11 07 53 am](https://cloud.githubusercontent.com/assets/701583/8323929/5834ccc4-1a68-11e5-99f3-2171d62cbd86.png)
    * Here are a couple of requests fired for the sample Arithmetic handler methods "add" and "multiply" using the [Arithmetic Client](https://github.com/Flipkart/phantom/blob/master/sample-thrift-proxy/src/main/java/thrift/ArithmeticClient.java). 
![screen shot 2015 06 24 at 11 08 47 am](https://cloud.githubusercontent.com/assets/701583/8324097/0d8f85e0-1a6a-11e5-9195-5fd211bd8057.png)
    * Sample Server Code is [here](https://github.com/Flipkart/phantom/tree/master/sample-thrift-proxy/src/main/java/thrift)
    * The Thrift IDL file for this is available on the  [Thrift Example](https://github.com/Flipkart/phantom/wiki/Getting-started-and-Examples) Wiki page
* Once you are able to run the sample, I presume you are now trying to run a Thrift proxy for your own service. Have you tried the instructions here : [Thrift Proxy](https://github.com/Flipkart/phantom/wiki/Thrift-proxy)? The easiest approach would be to edit the namesake files in "sample-thrift-proxy" module and replace relevant beans with your own service endpoint details. 
* Please share steps followed and the errors that you encountered. We can help debug the issue. 
* Do you still think a package of the sample thrift module (which is essentially contents of the Maven "target" directory) will help based on the above explanation/steps?

**Comment by MichaelF25** [comment]
Based on the thrift sample I've already created a maven project providing a thrift proxy for my service which runs fine if started from project root as described in the sample:
`java -cp "./target/*:./target/lib/*" \
org.trpr.platform.runtime.impl.bootstrap.BootstrapLauncher \
./src/main/resources/external/bootstrap.xml`

Usually I am using Spring Boot and therefore I am used to have a single executable jar for my application. Since Phantom/Trooper works different, I wanted to create a suitable distribution `.tar.gz` / `.zip` for deploying the proxy application.

Based on the thrift proxy sample I would like to see how to use the maven assembly plugin which would create such a packaged distribution including a suitable start script.

**Comment by regunathb** [comment]
You are right in your observation that Phantom/Trooper does not run well with an uber jar. This is because of various reasons including having the editable configurations outside the jar. We package Phantom deployments as .deb packages here at Flipkart. 
Just curious - are you facing issues in just packaging all of the binary jars under "target" and "/src/main/resources/external" into a tar package? Basically you need binaries (jar files under target) and config files (under /resources/external of your module) to be part of the package. If it helps, I can share the startup script we use to bring up Phantom.

**Comment by MichaelF25** [comment]
Yes, an example layout including start script of a packaged project would be helpful.
For example I've also tried to start inside the `target` folder my proxy app with this command line:

`java -cp "./*:./lib/*" org.trpr.platform.runtime.impl.bootstrap.BootstrapLauncher ./classes/external/bootstrap.xml`

Trooper starts but the xml config files (logback, spring bean definitions) are not found and therefore not loaded.

**Comment by regunathb** [comment]
While I get you the sample layout and startup script, let me also clarify something about how Trooper finds config files. Trooper can find any deployed file so long as it resides under a relative path of /resources/external (sort of convention like WEB-INF/lib for web archives). The root path from which this search occurs is called the 'projectsRoot' - this is defined in bootstrap.xml that you use to start your Trooper instance. If you see your file, this property refers to something like "$RUNTIME_CONFIG_PATH/../../../../" - here $RUNTIME_CONFIG_PATH is replaced with the absolute path of the bootstrap.xml that you are using i.e. in your case ./classes/external/ and depending in the backtracking ("../") that is added, the final project root is arrived at. Trooper will scan all "/resources/external" paths from this resolved project root while looking for files.

Sorry that this is not obvious at all currently. Maybe we will add a FAQ section where issues like this are explained. Can you try re-looking at where you have deployed your logback, spring bean definitions files and also at the 'projectsRoot' property value you are using?

**Comment by MichaelF25** [comment]
Thank you for the clarification about the `/resources/external` directory. This was the last missing piece which prevented my maven assembly from working.
Everything works now fine - my maven project creates a `.tar.gz` including startup script which just needs to be unpacked and started for deployment.

**Comment by regunathb** [comment]
Michael,

Notes on our build, deployment and startup artifacts for Phantom based runtimes:
* We package it as .deb files. Here is a sample file extract used to build phantom [Make Phantom](https://github.com/Flipkart/phantom/blob/master/docs/make-fk-w3-phantom-deb.sh)
* Configuration files, including all the files under /resources/external are pulled in from a hosted config service.
* We run using Java 6 or later. This is reflected in the startup script. Sample file : [Phantom startup](https://github.com/Flipkart/phantom/blob/master/docs/phantom_startup.sh)

**Comment by regunathb** [comment]
Great to see that you are now able to get it to work. Can you please close this issue if you consider it resolved?
