### ISSUE TITLE
how does phantom support cluster?

### ISSUE THREAD

**Issue by igool** [Flipkart/phantom#60]
does phantom  support in the distrubute environment?anything you talk, I would be very grateful!.thank you .

**Comment by regunathb** [comment]
Can you please provide more details on what is the distributed environment here? We run Phantom instances on 100s of machines. Individual Phantom instances however do not communicate/coordinate with each other though. The cluster-dashboard is the only cluster aware component that can monitor across the 100s of machines.

**Comment by igool** [comment]
ok.i got it.thanks
